# Generated by Django 4.2.6 on 2024-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_blog_remove_state_country_delete_city_delete_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
