# Generated by Django 4.2.6 on 2023-10-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField()),
                ('header', models.ImageField(upload_to='media')),
                ('footer', models.ImageField(upload_to='media')),
            ],
        ),
    ]
