# Generated by Django 4.2.6 on 2023-10-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optin',
            name='number',
            field=models.IntegerField(),
        ),
    ]
