# Generated by Django 4.2.6 on 2023-11-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0006_headerfooter_remove_optin_footer_remove_optin_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optin',
            name='HeaderFooter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='optin.headerfooter'),
        ),
    ]
