# Generated by Django 4.2.6 on 2023-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0007_alter_optin_headerfooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfooter',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
