# Generated by Django 4.2.6 on 2023-12-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0008_alter_headerfooter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerfooter',
            old_name='Name',
            new_name='name',
        ),
    ]
