# Generated by Django 4.2.6 on 2024-02-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0009_rename_name_headerfooter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optin',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
