# Generated by Django 4.2.6 on 2024-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techblog',
            name='short_discription',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='titale',
            field=models.CharField(max_length=100),
        ),
    ]
