# Generated by Django 4.2.6 on 2024-01-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techBlog', '0002_alter_techblog_short_discription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techblog',
            old_name='titale',
            new_name='title',
        ),
    ]
