# Generated by Django 4.2.6 on 2023-10-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0004_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optin',
            name='company',
        ),
        migrations.DeleteModel(
            name='company',
        ),
    ]
