# Generated by Django 4.2.6 on 2023-11-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0005_remove_optin_company_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('header', models.ImageField(upload_to='media')),
                ('footer', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='optin',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='optin',
            name='header',
        ),
        migrations.AddField(
            model_name='optin',
            name='HeaderFooter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optin.headerfooter'),
        ),
    ]
